# Generated by Django 5.1.5 on 2025-02-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_created_at_notification_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
