# Generated by Django 5.1.5 on 2025-02-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_date_created_notification_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date')},
        ),
    ]
